apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: simple-app-node-js-layers
  annotations:
    # The event we are targeting as seen from the webhook payload
    # this can be an array too, i.e: [pull_request, push]
    pipelinesascode.tekton.dev/on-event: "push"

    # The branch or tag we are targeting (ie: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "main"

    # How many runs we want to keep attached to this event
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    # The variable with brackets are special to Pipelines as Code
    # They will automatically be expanded with the events from Github.
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: app-dir
      value: source
    - name: imagestream-url
      value: image-registry.openshift-image-registry.svc:5000/tkn-pac-example-rhpds/my-app

    # Buildah step configuration parameters - storage driver and TLS settings.
    - name: TLSVERIFY
      value: 'false'
    - name: STORAGE_DRIVER
      value: vfs
      #
      #   Quay.io configuration
      #
    - name: quay-io-account
      value: "marrober"
    - name: quay-io-repository
      value: "simple-pipeline"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: app-dir
      - name: TLSVERIFY
      - name: STORAGE_DRIVER
      - name: imagestream-url
      - name: quay-io-account
      - name: quay-io-repository
    workspaces:
      - name: source
      - name: resources
    tasks:
      #  Git clone source content
      - name: fetch-repository
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
          - name: verbose
            value: 'false'
        taskRef:
          kind: ClusterTask
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        # Build the container
      - name: build
        params:
          - name: TLSVERIFY
            value: "$(params.TLSVERIFY)"
          - name: STORAGE_DRIVER
            value: $(params.STORAGE_DRIVER)
          - name: app-dir
            value: $(params.app-dir)
        taskRef:
          kind: Task
          name: build
        runAfter:
          - fetch-repository
        workspaces:
          - name: resources
            workspace: resources
          - name: source
            workspace: source
      - name: push-image-to-imagestream
        params:
        - name: imagestream-url
          value: $(params.imagestream-url)
        - name: STORAGE_DRIVER
          value: $(params.STORAGE_DRIVER)
        - name: TLSVERIFY
          value: "$(params.TLSVERIFY)"
        - name: pipelineRunName
          value: $(context.pipelineRun.name)
        taskRef:
          kind: Task
          name: push-image-to-ocp
        runAfter:
          - build
        workspaces:
          - name: resources
            workspace: resources
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: resources
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
