apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        # - image: ghcr.io/chmouel/gosmee:latest
        - name: gosmee
          image: image-registry.openshift-image-registry.svc:5000/pac-example/gosmee:latest
          imagePullPolicy: IfNotPresent
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/8tfqo5bJhqrWru1j",
              "https://pipelines-as-code-controller-openshift-pipelines.apps.celeron.demolab.local",
            ]
