FROM registry.access.redhat.com/ubi8/nodejs-18@sha256:8ab68f448964952fd12a45ee7c22ddf1aafba721b5ca32b741efdcfb279668ee
COPY layer.js /opt/app-root/src/layer.js
COPY node_modules/ /opt/app-root/src/node_modules/
USER 0
RUN chmod a+w /var/log
USER 1001
ENTRYPOINT ["node"]
CMD ["/opt/app-root/src/layer.js"]
