FROM default-route-openshift-image-registry.apps.cluster-qrbn4.qrbn4.sandbox2884.opentlc.com/tkn-pac-example-rhpds/node-js:latest
COPY layer.js /opt/app-root/src/layer.js
COPY node_modules/ /opt/app-root/src/node_modules/
USER 0
RUN chmod a+w /var/log
USER 1001
ENTRYPOINT ["node"]
CMD ["/opt/app-root/src/layer.js"]
